default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development
  username: root
  password:

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
